project:
  type: website

website:
  title: "cSVD burden project"
  site-url: https://agdamsbo.github.io/cSVD-burden-annotation-and-analysis-project/
  repo-url: https://github.com/agdamsbo/cSVD-burden-annotation-and-analysis-project
  repo-actions: [source, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: doc/plan.qmd
        text: Project plan
      - href: doc/down-to-work.qmd
        text: Annotation
      - href: doc/irr.qmd
        text: IRR
      - text: Resources
        menu:
        - href: doc/svd-score.qmd
          text: SVD scoring scale
        - href: doc/instrument.qmd
          text: REDCap data capture
    right:
      - icon: "github"
        href: https://github.com/agdamsbo/cSVD-burden-annotation-and-analysis-project
  page-footer:
    center:
      - text: "License: CC BY 4.0"
        href: LICENSE.html

format:
  html:
    theme: simplex

knitr:
  opts_chunk:
    echo: false

execute:
  freeze: true
  echo: false
  eval: false

editor:
  markdown:
    wrap: 72
    canonical: true

# author:
#   - name: Andreas
#     orcid: 0000-0002-7559-1154
#     email: andrlr@rm.dk
#     url: https://pure.au.dk/portal/en/persons/andreas-gammelgaard-damsbo(e3c4afce-3eba-4456-8b8b-2fd90775c87a).html
#     affiliations:
#       - ref: dsc
# affiliations:
#   - id: dsc
#     name: Danish Stroke Centre, AUH
#     department: Neurology
#     city: Aarhus
#     country: Denmark
#     url: https://www.en.auh.dk/departments/danish-stroke-centre/
