---
title: "Assessor information"
date: last-modified
format: 
  html: default
  docx: default
  pdf: default
editor: visual
toc: true
---

## Motivation

SVD in the brain is still uncharted territory. We have two large
datasets (possibly supplemented with additional projects) on acute
stroke patients that we have the opportunity to merge and link with data
from MRI scans. The first project is to investigate the relationship
between various lifestyle factors and the degree of SVD among stroke
patients. We also plan to use the data for other projects in the future.

## Annotation and capturing

No widely used scoring system exists, that considers all elements of SVD
on MRI. The Fazekas score is widely used, but only accounts for white
matter hyperintensities (WMH).

Based on existing studies, [we have developed a scoring tool for this
purpose](https://agdamsbo.github.io/cSVD-burden-annotation-and-analysis-project/doc/svd-score.html),
relying on FLAIR and T2\*/SWI sequences from the acute scans. We are
interested in microbleeds, superficial siderosis, previous lacunar
infarcts, white matter hyperintensities, and atrophy.

We have created a minimal registration tool in REDCap, that will later
be enriched with metadata on the scans.

## Participation

I want to invite you all to participate in this project. I will conduct
a short teaching session on the material (see later), and you will be
assigned a set number of subjects to evaluate.

The project will run in two phases. In total I hope to have around 1000
subjects scored. Depending on how many assessors are ready to help, the
math is pretty clear. The expected time use pr subject is 2-10 minutes
when everything is set up.

What you get for helping out:

-   Role as co-author on the first paper based on the data and possibly
    participate on later publications (normal criteria for
    participation)

-   Extensive experience evaluating SVD in acute stroke patients which
    will benefit you and your patients in the future

-   A big thank you!

-   Assess to all source code used for data acquisition and analyses
    (shared under an open source license)

-   
