---
title: "Allocation and workflow"
date: last-modified
format: 
  html: default
  pdf: default
  docx: default
editor: visual
---

## Allocation table {#sec-allocations}

```{r}
#| eval: true
#| echo: false
#| label: allocation-table
#| tbl-cap: Assessor allocation of subject IDs
source(here::here("data_local/local.R"))
source(here::here("R/functions.R"))

suppressMessages(
readODS::read_ods(here::here("data/allocation.ods")) |>
  (\(.x){
    split.default(.x, grepl(".2$", colnames(.x)))
  })() |>
  lapply(na.omit) |>
  lapply(setNames, c("assessor", "start", "stop")) |>
  lapply(function(.x) {
    .x |>
      dplyr::tibble(
        "ids" = paste0(start, "-", stop),
        allocated_assessor = multi_replace(assessor, key = assessor_key)
      ) |>
      dplyr::select(tidyselect::all_of(c(
        "allocated_assessor", "ids"
      )))
  }) |>
  dplyr::bind_rows() |>
  (\(.y){
    split(.y, .y$allocated_assessor)
  })() |>
  purrr::map(function(.z) {
    if (nrow(.z) > 1) {
      vals <- unique(.z[2][[1]])

      tibble::tibble(
        .z[[1]][1],
        paste0(vals, collapse = ", ")
      ) |> setNames(names(.z))
    } else {
      .z
    }
  }) |>
  dplyr::bind_rows() |>
  dplyr::arrange(purrr::map_chr(strsplit(ids,"-"),purrr::pluck,1) |> as.numeric()) |>
  setNames(c("assessor", "IDs (svd_)")) |> 
  knitr::kable()
)
```

## Suggested workflow {#sec-suggested-workflow}

**In REDCap:**

1.  Login to AU REDCap, open the "SVD-burden POOL" project and go to
    "**Record Status Dashboard**" ([just follow this
    link](https://redcap.au.dk/redcap_v13.7.21/DataEntry/record_status_dashboard.php?pid=8420&rd_id=3187))

2.  From the drop-down "**Dashboard displayed**", choose the desired
    dashboard (there is one common for the first, and one for each
    assessor with allocated subjects and progress).

3.  Open the "SVD score" instrument to start capturing the score.

    -   If the "dot" is colored, the instrument already has been filled.
        Press the "+"-sign to create a new version (mainly necessary
        during the inter-rater-reliability testing, as each subject is
        only scored once)

4.  In the top of the instrument, the patient CPR, name and admission
    time is printed as well as assessor allocated (should be you, but
    please check) and link to Citrix for convenience.

**In Citrix/PACS:**

5.  Open the "Billeddiagnostik PACS" module (find it under "APPS" and
    "star" it the first time) and look up the patient using the CPR
    number copied from REDCap.

6.  Please use the subject admission date and time as reference to
    select the correct scan and the exact date and time of the scan
    (fields are pre-filled with admission date and time).

7.  The scan might take a minute or two to load from the storage server.
    A little patience is necessary. The first time, you can use this
    time to arrange your program windows for optimal workflow.

    -   Maximise the "PACS" window on the left half of yuor screen and
        "REDCap" on the left (to have controls line up in the middle and
        minimize cursor movement)

        Note that the REDCap is organized by MRI sequences (T2\*/SWI and
        FLAIR) corresponding to how they are organized in PACS. The
        relevant sequences are usually found at the buttom of the list
        in PACS.

**In REDCap:**

8.  When done filling out all fields, you can save the data and go
    directly to the next subject by clicking "Save & Go To Next Record"

    -   The last item is "**Complete?**". Use "Incomplete" if
        interrupted, "Unverified" in case of doubt, "Complete" when
        completed.
    -   On the right and at the end of the instrument, there are two
        blue boxes. The top is "Save & Exit Form", the second have
        different options to choose from by clicking the arrow on the
        right. Choose "Save & Go To Next Record". Then repeat step 3-8.
