---
title: "SVD score tool"
date: 2024-01-02
editor: visual
format: 
  html: default
  pdf: default
headertext: Consensus paper on short SVD scoring for historical MR scans
toc: true
bibliography: references.bib
---

## Purpose

**Primary:** continuous scale for grading SVD burden, for possible use
in current as well as historical data.

**Secondary:** risk stratification of new stroke, dementia; correlation
to life style factors.

::: callout-caution
## Only intended for research use currently

The following scoring system is not formally published and has not been
through peer-review.
:::

## Scoring table {#sec-scorr}

| **MRI features**                                            | **Raw score** | Short score |
|-------------------------------------------------------------|---------------|-------------|
| **Number of microbleeds (*T2\*/SWI*)**                      |               |             |
| 0                                                           | 0             | 0           |
| 1                                                           | 1             | 1           |
| 2-4                                                         | 2             | 1           |
| 5-10                                                        | 3             | 1           |
| \>10                                                        | 4             | 1           |
| **Location of microbleeds -- no points (*T2\*/SWI*)**       |               |             |
| Lobar, deep, or infratentorial (choose one or more)         | L/D/I         | \-          |
| **Superficiel siderose (*T2\*/SWI*)**                       |               |             |
| No siderosis                                                | 0             | \-          |
| 1 sulcus                                                    | 1             | \-          |
| \>1 sulcus                                                  | 2             | \-          |
| **Lacunes (*FLAIR*)**                                       |               |             |
| 0                                                           | 0             | 0           |
| 1                                                           | 1             | 1           |
| 2                                                           | 2             | 1           |
| 3-5                                                         | 3             | 1           |
| \>5                                                         | 4             | 1           |
| **White matter hyperintensities -- see Figure 1 (*FLAIR*)** |               |             |
| Absent                                                      | 0             | 0           |
| Punctate foci                                               | 1             | 0           |
| Beginning confluence                                        | 2             | 1           |
| Large confluent areas                                       | 3             | 1           |
| **Atrophy - see Figure 2 (*FLAIR/T1*)**                     |               |             |
| No                                                          | 0             | 0           |
| Mild                                                        | 1             | 0           |
| Moderate                                                    | 2             | 1           |
| Severe                                                      | 3             | 1           |
| **Total SVD score**                                         | **0-16**      | **0-4**     |

: SVD score table {.striped .hover}

## Setting

The scoring system is intended for use with acute MRI stroke scans.
Scans are performed according to the acute stroke protocol at the given
time of scan. Available sequences are DWI, ADC, 2D FLAIR, and T2\* or
SWI in our setting, but if available 3D FLAIR and T1 sequences should be
used. Data capturing should reflect this, if data is later merged from
different populations.

Scoring is performed independently by trained neurologists.
Inter-rate-reliability-measures are performed to ensure validity.

### Different suggested scores

Inspired by the scores from

## Definitions on bio-markers

Definitions are mainly according to the STRIVE v1
criteria,[@wardlaw2013] with minor local specifications. The bio-markers
included are within the suggestions from @markus2022 in the FINESSE
framework.

### Microbleeds

Sequence: T2\*/SWI

Small (generally 2--5 mm in diameter, but sometimes up to 10 mm) areas
of signal void with associated blooming seen on SWI-weighted MRI.

Different cut-offs are used in different trials.[@akoudad2016] We try to
register in a way, so that our analysis can be made similarly to other
studies and to provide enough resolution.

As discussions about the importance of location is
ongoing,[@vernooij2008] we register if microbleeds are located lobar,
deep, or infratentorial.

### Superficial siderosis

Sequence: T2\*/SWI

"Investigators should describe the location of siderosis (i.e., the
number of sulci involved and in which lobes)."[@wardlaw2013, p. 828]

### Lacunar infarcts

Sequence: 2D/3D FLAIR

"A round or ovoid, subcortical, fluid-filled cavity (signal similar to
CSF) of between 3 mm and about 15 mm in diameter, consistent with a
previous acute small subcortical infarct or haemorrhage in the territory
of one perforating arteriole."[@wardlaw2013, p. 825]

Additionally: "We identified asymptomatic lacunar infarcts as sharply
demarcated hyperintense lesions \<20 mm on T2-weighted images with
corresponding hypointense lesions with a hyperintense rim on FLAIR. In
lacunar stroke patients, the lesion could not be compatible with the
clinical stroke."[@huijts2013]

Based on the practice by @olama2020 and the 2021 ESO guidelines on
covert small vessel disease, lacunes are counted 0, 1 , 2 , 3-5 and
\>5.[@wardlaw2021]

### White matter hyperintensities

Sequence: 2D/3D FLAIR

The Fazekas subscale for deep white matter is used. The scale divides
the white matter in periventricular and deep white matter, and each
region is given a grade depending on the size and confluence of
lesions.[@fazekas1987]

No regional differences is noted.[@degroot2000] Scoring is performed
with [visual
reference](https://radiopaedia.org/cases/fazekas-scale-for-white-matter-lesions?lang=us)
from [Radiopedia.org](https://radiopaedia.org/).

### Atrophy

Sequence: 2D/3D FLAIR or T1

We follow definitions for the Global Cerebral Atrophy (GCA)
score.[@harper2015]

A picture sample for reference is used.[@harper2015, figure 1]

## References

::: {#refs}
:::
